### ISSUE TITLE
Parameter 'all_bands' is set to False

### ISSUE THREAD

**Issue by aghand0ur** [sentinel-hub/water-observatory-backend#2]
Hello,

When running the following command, I run into an error:
`measurements = extract_surface_water_area_per_frame(42, nominal_outline, the_dam_bbox, date, resx, resy)
`
```
/usr/local/lib/python3.6/dist-packages/s2cloudless/S2PixelCloudDetector.py in get_cloud_probability_maps(self, X, **kwargs)
    105         if band_num != exp_bands:
    106             raise ValueError("Parameter 'all_bands' is set to {}. Therefore expected band data with {} bands, "
--> 107                              "got {} bands".format(self.all_bands, exp_bands, band_num))
    108 
    109         if self.all_bands:

ValueError: Parameter 'all_bands' is set to False. Therefore expected band data with 10 bands, got 9 bands
```

Any clues? This is most probably related to V3 Transition.

Ali

**Comment by batic** [comment]
Hi Ali,

Speaking from the top of my head, but you are probably right. The WCS request used to retrieve also the datamask (using Transparency keyword), which doesn't work work since the transition to V3. WCS request still perceives the last band as data mask, meaning that you end up with 9 (instead of 10) bands.

We will at some point update the code, but I cannot say when. In the mean time, pull requests are encouraged and appreciated.

**Comment by aghand0ur** [comment]
Hi @batic ,

I fixed the code related to V3 transition and will issue a pull request on this matter.
However, some of the scripts I had to fix are in the s2cloudless library on which BlueDot depends.

How things work in this case? shall I issue 2 different pull requests?

Ali

**Comment by batic** [comment]
Hi @aghand0ur,

Yes, please create two pull requests and we will coordinate them.

Best,
Matej

**Comment by aghand0ur** [comment]
@batic 
I created both pull requests.
Looking forward for your review.

Ali

**Comment by saheelBreezo** [comment]
Hey, this issue still persists. I did update the code with the changes from this PR but the issue still remains. I assume there another [PR](https://github.com/sentinel-hub/sentinel2-cloud-detector/pull/27) in `s2-cloud-detection` needs to be merge. Is is possible to tell the status of these PR's

**Comment by aghand0ur** [comment]
Hi @saheelBreezo,
yes you need to merge both updates. You can do it manually at your end while waiting for sentinel-hib guys @batic update.

Ali
